### ISSUE TITLE
Don't treat Capitalized method name as a Constant

### ISSUE THREAD

**Issue by jimweirich** [jimweirich/sorcerer#6]
The following output is from rspec-given with an expression containing Failure(...).  It incorrectly tries to treat "Failure" as a constant.

``` ruby
Failures:

  1) Something exceptions 
     Failure/Error: Then { result == Failure(StandardError, "OUCH") }
       Then expression failed at /Users/jim/working/git/rspec-given/pkg/sample_spec.rb:16
       expected: :ok
       to equal: <Failure on StandardError matching /\AOUCH\Z/>
         false           <- result == Failure(StandardError, "OUCH")
         :ok             <- result
         <Failure on StandardError matching /\AOUCH\Z/>
                         <- Failure(StandardError, "OUCH")
         StandardError   <- StandardError
         NameError: uninitialized constant Failure
                         <- Failure
     # /Users/jim/working/git/rspec-given/lib/given/rspec/framework.rb:24:in `fail_with'
     # /Users/jim/working/git/rspec-given/lib/given/module_methods.rb:62:in `fail_with'
     # /Users/jim/working/git/rspec-given/lib/given/extensions.rb:110:in `_gvn_naturally_assert'
     # /Users/jim/working/git/rspec-given/lib/given/extensions.rb:102:in `_gvn_evaluate'
     # /Users/jim/working/git/rspec-given/lib/given/extensions.rb:93:in `_gvn_then'
     # ./sample_spec.rb:16:in `block in Then'

Finished in 0.0017 seconds
1 example, 1 failure
```

**Comment by jimweirich** [comment]
Fixed in 0.3.11
